### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by Diego74965** [saurabh1e/open-pos#1]
I've done all the steps but when i do the last one 
`ng serve`
this error pop up 

> You have to be inside an angular-cli project in order to use the serve command.

**Comment by hammadcapricorn** [comment]
I am facing same issue

**Comment by saurabh1e** [comment]
Hi,
I abandoned the project last year. The code is incomplete and all the dependencies are outdated.
Quite a few people have asked about this project, I will be working on this soon by end of this month I will update the code and dependencies and fix whatever bugs are here.

**Comment by saurabh1e** [comment]
Working on https://github.com/saurabh1e/pos
